packages:
  - demo/*
  - docs
  - editor/*
  - packages/*
  - packages/*/playground
  - plugins/*
  - templates/*
  - themes/*
catalog:
  '@antfu/eslint-config': 2.9.0
  '@antfu/ni': ^25.0.0
  '@antfu/utils': ^9.2.0
  '@babylonjs/core': 5.19.0
  '@babylonjs/gui': 5.19.0
  '@babylonjs/loaders': 5.19.0
  '@babylonjs/materials': 5.19.0
  '@faker-js/faker': ^9.8.0
  '@google/model-viewer': ^4.1.0
  '@iconify-json/carbon': ^1.2.8
  '@iconify-json/ep': ^1.2.2
  '@iconify-json/file-icons': ^1.2.1
  '@iconify-json/logos': ^1.2.4
  '@iconify-json/mdi': ^1.2.3
  '@iconify-json/radix-icons': ^1.2.2
  '@iconify-json/ri': ^1.2.5
  '@iconify-json/twemoji': ^1.2.2
  '@iconify-json/vscode-icons': ^1.2.22
  '@iconify/vue': ^5.0.0
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@nuxt/devtools': ^2.4.1
  '@nuxtjs/color-mode': ^3.5.2
  '@pinia/nuxt': ^0.11.0
  '@playwright/test': ^1.52.0
  '@radix-ui/colors': ^3.0.0
  '@shikijs/markdown-it': ^3.4.2
  '@types/fs-extra': ^11.0.4
  '@types/howler': ^2.2.12
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/mdast': 4.0.3
  '@types/node': ^22.15.29
  '@types/nprogress': ^0.2.3
  '@types/prompts': ^2.4.9
  '@types/semver': ^7.7.0
  '@types/splitpanes': ^2.2.6
  '@types/unist': ^3.0.3
  '@types/wicg-file-system-access': ^2023.10.6
  '@types/xml2js': ^0.4.14
  '@types/yargs': ^17.0.33
  '@unhead/vue': ^2.0.10
  '@unocss/eslint-config': ^66.1.3
  '@unocss/eslint-plugin': ^66.1.3
  '@unocss/nuxt': ^66.1.3
  '@vite-pwa/nuxt': ^1.0.3
  '@vitejs/plugin-vue': ^5.2.4
  '@vue-flow/core': ^1.44.0
  '@vueuse/core': ^13.3.0
  '@vueuse/head': ^2.0.0
  '@vueuse/motion': ^3.0.3
  '@vueuse/nuxt': ^13.3.0
  '@vueuse/sound': ^2.1.3
  '@webgpu/types': ^0.1.61
  animate.css: ^4.1.1
  babylon-vrm-loader: ^2.0.0
  baklavajs: 2.4.3
  benny: ^3.7.1
  bumpp: ^10.1.1
  c12: ^3.0.4
  colord: ^2.9.3
  consola: ^3.4.2
  cross-env: ^7.0.3
  dayjs: ^1.11.13
  debug: ^4.4.1
  defu: ^6.1.4
  eslint: ^9.28.0
  eslint-plugin-format: ^1.0.1
  fast-deep-equal: ^3.1.3
  fs-extra: ^11.3.0
  global-directory: ^4.0.1
  hast-util-to-html: ^9.0.5
  honeycomb-grid: ^4.1.5
  hookable: ^5.5.3
  howler: ^2.2.4
  html2canvas: ^1.4.1
  https-localhost: ^4.7.1
  husky: ^9.1.7
  jiti: ^2.4.2
  js-yaml: ^4.1.0
  lint-staged: ^16.1.0
  markdown-it-link-attributes: ^4.0.1
  mdast-util-to-hast: ^13.2.0
  monaco-editor: ^0.52.2
  nodemon: ^3.1.10
  npm-run-all: ^4.1.5
  nprogress: ^0.2.0
  nuxt: 3.17.2
  open: ^10.1.2
  pathe: ^2.0.3
  pinia: ^3.0.2
  pixi-painter: ^0.1.6-beta.1
  pixi.js: 8.0.4
  prism-theme-vars: ^0.2.5
  prompts: ^2.4.2
  rehype-stringify: ^10.0.1
  reka-ui: ^2.3.0
  remark: ^15.0.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.1
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.2
  resolve: ^1.22.10
  resolve-global: ^2.0.0
  rimraf: ^6.0.1
  sass: ^1.89.1
  semver: ^7.7.2
  splitpanes: ^4.0.4
  swiper: ^11.2.8
  to-vfile: ^8.0.0
  tsdown: ^0.12.6
  tsx: ^4.19.4
  typedoc: ^0.28.5
  typedoc-plugin-merge-modules: ^7.0.0
  typescript: 5.6.3
  unbuild: ^3.5.0
  unified: ^11.0.5
  unist-builder: ^4.0.0
  unist-util-visit: ^5.0.0
  unocss: ^66.1.3
  unplugin-vue-components: ^28.7.0
  unplugin-vue-markdown: ^28.3.1
  unplugin-vue-router: ^0.12.0
  unstorage: ^1.16.0
  v-tooltip: ^4.0.0-beta.17
  vfile-matter: ^5.0.1
  vite: ^6.3.5
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-dts: ^4.5.4
  vite-plugin-inspect: ^11.1.0
  vite-plugin-pwa: ^1.0.0
  vite-plugin-vue-devtools: ^7.7.6
  vite-plugin-vue-layouts: ^0.11.0
  vite-ssg: 0.23.6
  vitepress: 1.0.1
  vitest: ^3.1.4
  vue: ^3.5.16
  vue-demi: ^0.14.10
  vue-i18n: ^11.1.5
  vue-router: ^4.5.1
  vue-tsc: ^2.2.10
  wc-github-corners: ^0.1.6
  xml2js: ^0.6.2
  yargs: ^18.0.0
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - esbuild
  - unrs-resolver
onlyBuiltDependencies:
  - vue-demi
