packages:
  - demo/*
  - docs
  - editor/*
  - packages/*
  - packages/*/playground
  - templates/*
catalog:
  '@antfu/eslint-config': 2.9.0
  '@antfu/ni': ^0.23.1
  '@antfu/utils': ^0.7.10
  '@babylonjs/core': 5.19.0
  '@babylonjs/gui': 5.19.0
  '@babylonjs/loaders': 5.19.0
  '@babylonjs/materials': 5.19.0
  '@faker-js/faker': ^9.3.0
  '@google/model-viewer': ^4.0.0
  '@headlessui/vue': ^1.7.23
  '@iconify-json/carbon': ^1.2.4
  '@iconify-json/ep': ^1.2.1
  '@iconify-json/file-icons': ^1.2.0
  '@iconify-json/logos': ^1.2.3
  '@iconify-json/mdi': ^1.2.1
  '@iconify-json/radix-icons': ^1.2.1
  '@iconify-json/ri': ^1.2.3
  '@iconify-json/twemoji': ^1.2.1
  '@iconify-json/vscode-icons': ^1.2.3
  '@iconify/vue': ^4.2.0
  '@intlify/unplugin-vue-i18n': ^6.0.1
  '@nuxt/devtools': ^1.6.3
  '@nuxtjs/color-mode': ^3.5.2
  '@pinia/nuxt': ^0.9.0
  '@playwright/test': ^1.49.0
  '@radix-ui/colors': ^3.0.0
  '@shikijs/markdown-it': ^1.24.0
  '@types/fs-extra': ^11.0.4
  '@types/howler': ^2.2.12
  '@types/js-yaml': ^4.0.9
  '@types/markdown-it-link-attributes': ^3.0.5
  '@types/mdast': 4.0.3
  '@types/node': ^22.10.1
  '@types/nprogress': ^0.2.3
  '@types/prompts': ^2.4.9
  '@types/semver': ^7.5.8
  '@types/splitpanes': ^2.2.6
  '@types/unist': ^3.0.3
  '@types/wicg-file-system-access': ^2023.10.5
  '@types/xml2js': ^0.4.14
  '@types/yargs': ^17.0.33
  '@unhead/vue': ^1.11.13
  '@unocss/eslint-config': ^0.65.1
  '@unocss/nuxt': ^0.65.1
  '@vite-pwa/nuxt': ^0.10.6
  '@vitejs/plugin-vue': ^5.2.1
  '@vueuse/core': ^12.0.0
  '@vueuse/head': ^2.0.0
  '@vueuse/motion': ^2.2.6
  '@vueuse/nuxt': ^12.0.0
  '@vueuse/sound': ^2.0.1
  '@webgpu/types': ^0.1.51
  animate.css: ^4.1.1
  babylon-vrm-loader: ^2.0.0
  baklavajs: 2.4.3
  benny: ^3.7.1
  bumpp: ^9.8.1
  c12: ^2.0.1
  colord: ^2.9.3
  consola: ^3.2.3
  critters: ^0.0.25
  cross-env: ^7.0.3
  dayjs: ^1.11.13
  debug: ^4.4.0
  defu: ^6.1.4
  electron: ^33.2.1
  electron-builder: ^25.1.8
  eslint: 8.57.0
  eslint-plugin-format: ^0.1.3
  fast-deep-equal: ^3.1.3
  fs-extra: ^11.2.0
  global-directory: ^4.0.1
  hast-util-to-html: ^9.0.3
  honeycomb-grid: ^4.1.5
  hookable: ^5.5.3
  howler: ^2.2.4
  html2canvas: ^1.4.1
  https-localhost: ^4.7.1
  husky: ^9.1.7
  import-from: ^4.0.0
  is-installed-globally: ^1.0.0
  jiti: ^2.4.1
  js-yaml: ^4.1.0
  kolorist: ^1.8.0
  lint-staged: ^15.2.10
  markdown-it-link-attributes: ^4.0.1
  mdast-util-to-hast: ^13.2.0
  monaco-editor: ^0.52.0
  nodemon: ^3.1.7
  npm-run-all: ^4.1.5
  nprogress: ^0.2.0
  nuxt: ^3.14.1592
  open: ^10.1.0
  pathe: ^1.1.2
  picocolors: ^1.1.1
  pinia: ^2.3.0
  pixi-painter: ^0.1.6-beta.1
  pixi.js: 8.0.4
  playwright-chromium: ^1.49.0
  prism-theme-vars: ^0.2.5
  prompts: ^2.4.2
  radix-vue: ^1.9.11
  rehype-stringify: ^10.0.1
  remark: ^15.0.1
  remark-frontmatter: ^5.0.0
  remark-gfm: ^4.0.0
  remark-parse: ^11.0.0
  remark-rehype: ^11.1.1
  resolve: ^1.22.8
  resolve-from: ^5.0.0
  resolve-global: ^2.0.0
  rimraf: ^6.0.1
  sass: ^1.82.0
  semver: ^7.6.3
  splitpanes: ^3.1.5
  swiper: ^11.1.15
  to-vfile: ^8.0.0
  tsup: ^8.3.5
  tsx: ^4.19.2
  typedoc: ^0.27.3
  typedoc-plugin-markdown: 4.0.0-next.23
  typedoc-plugin-merge-modules: ^6.1.0
  typedoc-vitepress-theme: 1.0.0-next.10
  typescript: 5.6.3
  unbuild: ^2.0.0
  unified: ^11.0.5
  unist-builder: ^4.0.0
  unist-util-visit: ^5.0.0
  unocss: ^0.65.1
  unplugin-vue-components: ^0.27.5
  unplugin-vue-markdown: ^0.27.1
  unplugin-vue-router: ^0.10.9
  unstorage: ^1.13.1
  v-tooltip: ^4.0.0-beta.17
  vfile-matter: ^5.0.0
  vite: ^6.0.3
  vite-plugin-css-injected-by-js: ^3.5.2
  vite-plugin-dts: ^4.3.0
  vite-plugin-electron: ^0.29.0
  vite-plugin-electron-renderer: ^0.14.6
  vite-plugin-inspect: ^0.10.3
  vite-plugin-pwa: ^0.21.1
  vite-plugin-vue-devtools: ^7.6.7
  vite-plugin-vue-layouts: ^0.11.0
  vite-ssg: 0.23.6
  vitepress: 1.0.1
  vitest: ^2.1.8
  vue: ^3.5.13
  vue-demi: ^0.14.10
  vue-i18n: ^10.0.5
  vue-router: ^4.5.0
  vue-tsc: ^2.1.10
  wc-github-corners: ^0.1.6
  xml2js: ^0.6.2
  yargs: ^17.7.2
