packages:
  - demo/*
  - docs
  - editor/*
  - packages/*
  - packages/*/playground
  - plugins/*
  - templates/*
  - themes/*
  - playground

catalogs:
  babylon:
    '@babylonjs/core': 5.19.0
    '@babylonjs/gui': 5.19.0
    '@babylonjs/loaders': 5.19.0
    '@babylonjs/materials': 5.19.0
    babylon-vrm-loader: ^2.0.0
  build:
    '@intlify/unplugin-vue-i18n': ^6.0.8
    '@nuxt/devtools': ^2.5.0
    '@nuxtjs/color-mode': ^3.5.2
    '@pinia/nuxt': ^0.11.1
    '@shikijs/markdown-it': ^3.7.0
    '@unocss/eslint-config': ^66.3.1
    '@unocss/nuxt': ^66.3.1
    '@vite-pwa/nuxt': ^1.0.4
    '@vitejs/plugin-vue': ^5.2.4
    '@vueuse/nuxt': ^13.4.0
    beasties: ^0.3.4
    markdown-it-link-attributes: ^4.0.1
    nuxt: ^3.17.5
    rollup: ^4.44.0
    sass: ^1.89.2
    shiki: ^3.7.0
    tsdown: ^0.12.8
    unbuild: ^3.5.0
    unocss: ^66.3.1
    unplugin: ^2.3.5
    unplugin-auto-import: ^19.3.0
    unplugin-vue-components: ^28.7.0
    unplugin-vue-markdown: ^28.3.1
    unplugin-vue-router: ^0.12.0
    vite: ^7.0.0
    vite-bundle-visualizer: ^1.2.1
    vite-plugin-css-injected-by-js: ^3.5.2
    vite-plugin-dts: ^4.5.4
    vite-plugin-inspect: ^11.2.0
    vite-plugin-pwa: ^1.0.0
    vite-plugin-vue-devtools: ^7.7.7
    vite-plugin-vue-layouts: ^0.11.0
    vite-ssg: ^27.0.1
    vite-ssg-sitemap: ^0.9.0
  cli:
    cli-progress: ^3.12.0
    consola: ^3.4.2
    execa: ^9.6.0
    minimist: ^1.2.8
    npm-run-all: ^4.1.5
    prompts: ^2.4.2
    yargs: ^18.0.0
  dev:
    '@antfu/eslint-config': ^4.16.1
    '@faker-js/faker': ^9.8.0
    '@unocss/eslint-plugin': ^66.3.1
    cypress: ^14.5.0
    cypress-vite: ^1.6.0
    eslint: ^9.29.0
    eslint-plugin-format: ^1.0.1
    https-localhost: ^4.7.1
    husky: ^9.1.7
    lint-staged: ^16.1.2
    nodemon: ^3.1.10
    taze: ^19.1.0
    tsx: ^4.20.3
    typescript: ^5.8.3
    vue-tsc: ^2.2.10
  docs:
    typedoc: ^0.28.5
    typedoc-plugin-merge-modules: ^7.0.0
    vitepress: ^1.6.3
  frontend:
    '@google/model-viewer': ^4.1.0
    '@unhead/vue': ^2.0.11
    '@unocss/reset': ^66.3.1
    '@vue-flow/core': ^1.45.0
    '@vueuse/core': ^13.4.0
    '@vueuse/motion': ^3.0.3
    '@vueuse/sound': ^2.1.3
    animate.css: ^4.1.1
    colord: ^2.9.3
    howler: ^2.2.4
    html2canvas: ^1.4.1
    monaco-editor: ^0.52.2
    nprogress: ^0.2.0
    pinia: ^3.0.3
    pixi-painter: ^0.1.6-beta.1
    pixi.js: 8.0.4
    reka-ui: ^2.3.1
    splitpanes: ^4.0.4
    swiper: ^11.2.8
    vue: ^3.5.17
    vue-i18n: ^11.1.7
    vue-router: ^4.5.1
    wc-github-corners: ^0.1.6
  icons:
    '@iconify-json/carbon': ^1.2.10
    '@iconify-json/ep': ^1.2.2
    '@iconify-json/file-icons': ^1.2.1
    '@iconify-json/logos': ^1.2.4
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/radix-icons': ^1.2.2
    '@iconify-json/ri': ^1.2.5
    '@iconify-json/svg-spinners': ^1.2.2
    '@iconify-json/twemoji': ^1.2.2
    '@iconify-json/vscode-icons': ^1.2.23
    '@iconify/vue': ^5.0.0
  test:
    '@playwright/test': ^1.53.1
    '@vue/test-utils': ^2.4.6

    vitest: ^3.2.4
  types:
    '@types/cli-progress': ^3.11.6
    '@types/fs-extra': ^11.0.4
    '@types/howler': ^2.2.12
    '@types/js-yaml': ^4.0.9
    '@types/markdown-it-link-attributes': ^3.0.5
    '@types/mdast': ^4.0.4
    '@types/node': ^24.0.4
    '@types/nprogress': ^0.2.3
    '@types/prompts': ^2.4.9
    '@types/qrcode': ^1.5.5
    '@types/semver': ^7.7.0
    '@types/splitpanes': ^2.2.6
    '@types/unist': ^3.0.3
    '@types/wicg-file-system-access': ^2023.10.6
    '@types/xml2js': ^0.4.14
    '@types/yargs': ^17.0.33
    '@webgpu/types': ^0.1.61
  unified:
    hast-util-to-html: ^9.0.5
    mdast-util-to-hast: ^13.2.0
    rehype-stringify: ^10.0.1
    remark: ^15.0.1
    remark-frontmatter: ^5.0.0
    remark-gfm: ^4.0.1
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    to-vfile: ^8.0.0
    unified: ^11.0.5
    unist-builder: ^4.0.0
    unist-util-visit: ^5.0.0
    vfile-matter: ^5.0.1
  utils:
    '@antfu/ni': ^25.0.0
    '@antfu/utils': ^9.2.0
    benny: ^3.7.1
    bumpp: ^10.2.0
    c12: ^3.0.4
    cross-env: ^7.0.3
    dayjs: ^1.11.13
    debug: ^4.4.1
    defu: ^6.1.4
    fast-deep-equal: ^3.1.3
    fs-extra: ^11.3.0
    global-directory: ^4.0.1
    honeycomb-grid: ^4.1.5
    hookable: ^5.5.3
    jiti: ^2.4.2
    js-yaml: ^4.1.0
    open: ^10.1.2
    pathe: ^2.0.3
    resolve: ^1.22.10
    resolve-global: ^2.0.0
    rimraf: ^6.0.1
    semver: ^7.7.2
    unstorage: ^1.16.0
    xml2js: ^0.6.2
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - bufferutil
  - esbuild
  - unrs-resolver
