name: ADV.JS Demo

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: 📦 Install
        run: pnpm install

      - name: 🔧 Build ADV.JS CLI
        run: pnpm run build:advjs

      - name: 🎮 Build ADV.JS Demo
        run: pnpm run build:demo
